### PR TITLE
docker, Update and rename nodejs.yml to build.yml

### PR DESCRIPTION
**Pull request by larshp**

### CODE REVIEW

**Comment by sbcgua** [comment]
a bit arguable step to remove docker.yml. What is the trigger to rebuild the image ? The problem of this repo is that it can be: either own code update or abaplint code update. Consequently both should trigger the build. For such case docker tag should be a combination of versions e.g. `v2.3.1-0.90` (where 2.3.1 is abaplint and 0.90 docker backend logic). Imho

**Comment by larshp** [comment]
every push to master updates the docker image

dependabot pushes when there are changes to abaplint

currently the version is just the commit number, https://github.com/abaplint/abaplint-cloud-foundry/blob/master/.github/workflows/build.yml#L45, to get something running

I agree that the version should be something like `v2.3.1-0.90`, suggest commit number + version, like `56-v2.34.1`

**Comment by sbcgua** [comment]
> dependabot pushes when there are changes to abaplint

Ah ! smart :) I didn't think about such cool option.

> commit number + version, like 56-v2.34.1

Guess it won't do in a long run when stability requirement come up. But for now looks fine.

**Comment by larshp** [comment]
it needs a few tweaks, but its running 😄

**Pull request merged**
