### PR TITLE
Api shape

### PR DESCRIPTION
**Pull request by sbcgua**
#27 - api part
Unify api shape to:

```
{ success: 1, payload: ... }
{ success: 0, error: ... }
```

### CODE REVIEW

**Comment by sbcgua** [comment]
@larshp will do the corresponding part in abap backend , then release from wip. So in fact ready for review.

One place which looks ugly to me is: `try/catch` in `post("/check_file")`. I think this should be in the error handler below. But how to identify that this was an abaplint exception ?  Is there an Error subclass in abaplint ?

**Comment by larshp** [comment]
error subclass, no there is not opening an issue

**Comment by sbcgua** [comment]
yeah, would be nice. Well, then that `try/catch` will live here for a while ...

**Comment by sbcgua** [comment]
ready for review in connection with https://github.com/abaplint/abaplint-abap-backend/pull/19

**Pull request merged**
