### PR TITLE
ci changes

### PR DESCRIPTION
**Pull request by larshp**
@sbcgua I guess `jest` also does compilation?

### CODE REVIEW

**Comment by sbcgua** [comment]
yes, on the fly. and ts-node. and nodemon. So build is not produced unless `npm run build`. This may be important in future docker setups. But I'm going to check it.

P.S. I'd propose to do similar for abaplint itself, the scripts certainly needs some cleanup, do you mind ? ;) I'll post an issue with ideas when I get to that.

P.P.S why do you prefer "post***" scripts ? It actually obscures what is happening. Imho. Is it intentional ?

**Comment by larshp** [comment]
abaplint: suggestions welcome, but take care of runtime, last when I tested jest it was slower(perhaps I did something wrong), and I want to end up with code that can be run.

post: suggestions welcome

**Comment by sbcgua** [comment]
"...end up with code that can be run" - sure. :+1:

"post" scripts: well, the suggestion was to keep them separately, that what was in the original code you changed :) So I wanted to know why. Actually the lint following test makes sense. But I wanted to understand your reasoning, because in my opinion scripts are scripts and devops is devops - so seeing that we require test AND lint in github actions makes more sense to me than digging into npm sideeffects.

**Comment by larshp** [comment]
so

`"test": "jest && npm run lint",`

instead?

**Comment by larshp** [comment]
if all stuff is separated, then I have to look into github actions side effects

**Comment by sbcgua** [comment]
mmm, I think it is a conceptional discussion... Here is what I think - it all goes from usage scenarios.

1) if you frequently run `npm test` manually and so what to check both test and linter in one command - this makes perfect sense. I have no problem with it. Then both options (`&&` and `posttest`) are fine. This is npm flow a developer is using for himself.
2) If we talk about devops flow, it is different: let's say I'm a newcomer, doing a PR, and want to see what checks are done. I go to GA workflow (best place to see it!) and see "the check list" - that test are mandatory and I have to care about them. Then appears that linter is also mandatory but it is not obvious from the workflow, it is indirect. This is imho bad.

But anyway, you control the code so you set the rules. I just want to understand if this rule is grounded or just historically happened (then I can suggest a grounded one from my side :). Again for test/posttest - this makes sense to me. I'm more speaking for entangled scripts of main abaplint. So maybe this discussion should be in a dedicated issue :)

**Comment by larshp** [comment]
`npm install` followed by `npm test` I would say is the typical steps for a npm based project, so I put as much into it as possible. Trying to avoid having to remember and read package.json.

entangled scripts of main abaplint: yes, its entangled, and could use some work 😅

**Pull request merged**
