### PR TITLE
move docker files to root

### PR DESCRIPTION
**Pull request by larshp**
🤷‍♂️

### CODE REVIEW

**Comment by sbcgua** [comment]
mmm ? isn't it more cluttered like this ?

**Comment by larshp** [comment]
yea, but I could not get the docker/build-push-action action to work without doing this, pull request welcome

**Comment by sbcgua** [comment]
@larshp do you remember what exactly failed ? Or maybe a link to a build log ... I'll try to fix

**Comment by larshp** [comment]
nah, just try again, I'll give you access to merge PRs if you dont already have it

**Pull request merged**
