### PR TITLE
More structure

### PR DESCRIPTION
**Pull request by sbcgua**
- added dotenv, logging, helmet
- split server and app (for testing in particular)
- separate api
- basic smoke unit test
- some signal/exception stuff

TODO:
- unify form of api response
- basic validation (library or in-place ...)
- better abaplint exception handling

### CODE REVIEW

**Comment by larshp** [comment]
dont add more to this PR, if its working

there is a lot of different parts happening

**Comment by sbcgua** [comment]
ok. I'll doublecheck it a bit later and release from WIP.

By the way i potentially closes #2 (depending on what was the intention)

Also a question regarding #1 : a framework - could be cool but isn't it an overkill ? Just a question

**Comment by sbcgua** [comment]
by the way it actually works ... but I change the shape of the API checkobject api... so will need a fix from abap side as well

**Comment by sbcgua** [comment]
OK, so actually it works. tests (sinlge one :)) ) pass. Postman works. Importantly - the backend will not work for now as I changed api response shape (I will fix there). Also I commented out the "addInfo" so far - I think it should be a separate issue to understand what is required there

**Comment by larshp** [comment]
suggest rolling back the breaking changes and introducing breaking changes in a separate PR

**Comment by sbcgua** [comment]
Ok, agree

**Comment by sbcgua** [comment]
checked the code. I actually forgot to rewrite `check_object` to the new  api shape, just the ping :D 
so should work with the existing abapend for now. (abapend - it is a new term I guess)

**Comment by sbcgua** [comment]
can we merge ? I have some docker stuff in the pipeline :)

**Comment by larshp** [comment]
will have a look during the weekend, dont have much time this week

**Comment by larshp** [comment]
so, the `cf push` does not work anymore after #16, moving ts-node and typescript to a runtime dependency will probably solve it, but it does not seem very nice

suggest going back to the
`"start": "tsc && node build/server.js"`

**Comment by sbcgua** [comment]
will have a look a bit later. But from the top of my head - maybe the start command should not be `npm start`, but directly `node build/server.js`. Npm may swallow termination signals, it is kind of not encouraged for production. And changing start script this way will ruin other flows, nodemon in particular.

**Comment by sbcgua** [comment]
hmmm, what does the cf push checks to start the script by the way ? I'm not familiar with cf =( Is there are  some docs ?

**Comment by sbcgua** [comment]
conceptually it should be something like here: https://github.com/sbcgua/abaplint-cloud-foundry/blob/docker/docker/Dockerfile

```
npm ci
npm run build
npm prune --production
node build/server.js
```

**Comment by larshp** [comment]
it runs https://github.com/abaplint/abaplint-cloud-foundry/blob/master/manifest.yaml#L9, within https://docs.cloudfoundry.org/buildpacks/node/index.html

I use https://cockpit.hanatrial.ondemand.com/ for testing CF, free trial by SAP

**Comment by sbcgua** [comment]
Well, I read some links - it is quite obscure how and where cf does the actual preparation (npm install in particular) ... also examples - https://github.com/drnic/cf-sample-app-nodejs-typescript - do have separate build and run in package.json but just npm start in the manifest (???)

I have the following ideas for now:

1) The quickest: add a script - `"start:cf": "npm run build && node build/server.js"` and put it to manifest instead of `start` - could you try ?
2) there is some scn post mentioning some `mta.yaml` where several deployment commans can be given, but quite unclear from the first glance... - https://blogs.sap.com/2019/07/01/cloudfoundryfun-6-run-typescript-apps-on-cloud-foundry/
3) deploy with docker ? https://docs.cloudfoundry.org/devguide/deploy-apps/push-docker.html - most unified option in the long run !

**Comment by larshp** [comment]
fixed in https://github.com/abaplint/abaplint-cloud-foundry/commit/72c7e5ec9be05accfdb0d6e5ad76a3130062a20a, not super nice, but it runs

**Comment by sbcgua** [comment]
But why ? What's wrong with the `start:cf` suggestion ? What's wrong with the proposed scripts ?

**Comment by larshp** [comment]
suggestions welcome, but I dont want to spend too much time researching, just need something that can run

**Comment by larshp** [comment]
runs = on cloud foundry and locally(eg http://sci.abaplint.org)

**Comment by sbcgua** [comment]
Yes, so this PR is a suggestion. I did the study, this part is done. I spent some time and effort, read some posts picking good things. Considered different scenarios: development, testing, production. All to be consistent. With good clear naming. Wihtou unnecessary `&&`. Maintainable, reusable. On the cf subject I made 3 (!) proposal one of which should run from scratch. And canceling it with just "not super nice, but it runs" ... Sorry, but this is very demotivating. (and not the first time either).

**Comment by larshp** [comment]
Sorry, I feel the same, master worked previously, I don't want to spend hours fixing it, its very demotivating

the main problem with the PR is that it does not run in the environment that it is intended to run on, I'm not challenging the content

**Comment by sbcgua** [comment]
to summarize owr conversation in chat and in general. I think there should be clear criteria of "master works". Better to be defined somewhere openly like contribution.md or readme. Or at least clearly communicated in the comments. But not via direct adjustment of the code. A contributor might not be against some extra effort if clearly end reasonably communicated.

Anyway coming back to the constructive. I'll have a look at CF. Any links with "howtos" would be helpful. Is it same idea like in non-sap PaaS platforms ?

Long term: I'm really not sure that CF is the major solution for such a tool (although judging from my statistics). I think docker will have at least similar popularity among the enterprises. I have clients with own servers, with azure, but no one with cf. So I'd suggest to widen the "master works" criteria, maybe even renaming the repo ...

**Comment by larshp** [comment]
howtos: only the buildpack link, https://docs.cloudfoundry.org/buildpacks/node/index.html, I have not focused much on deployment and structure

> sure that CF is the major solution for such a tool

agree, just wanted something that fits into the SAP story. This is a difficult area, CF handles scaling quite well, node runs in a single thread so this is an issue with the current implementation. Running this code in a 100+ developers setup probably doesnt work right now, solving this might bring us into the area of Kubernetes / Knative / Kyma, which is uncharted territory for me

**Comment by larshp** [comment]
taking a look at this now, trying to get this branch running on CF

**Comment by larshp** [comment]
-> https://github.com/abaplint/abaplint-cloud-foundry/pull/24

**Comment by larshp** [comment]
large parts of this PR merged via #24

closing

**Pull request closed without merging**
